/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import Controlador.ControladorDialegCpu;

/**
 *
 * @author marc
 */
public class addDialog extends javax.swing.JDialog {

    /**
     * Creates new form addDialog
     */
    
    private ControladorDialegCpu ctrl;
    public addDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        acceptButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        codiLabelShow = new javax.swing.JLabel();
        nomLabelShow = new javax.swing.JLabel();
        tipusLabelShow = new javax.swing.JLabel();
        dataLabelShow = new javax.swing.JLabel();
        fabricantLabelShow = new javax.swing.JLabel();
        coresLabelShow = new javax.swing.JLabel();
        optionalLabelShow = new javax.swing.JLabel();
        preuLabelShow = new javax.swing.JLabel();
        preuTextField = new javax.swing.JTextField();
        igpuCheckBox = new javax.swing.JCheckBox();
        overclockCheckBox = new javax.swing.JCheckBox();
        intelRadioButton = new javax.swing.JRadioButton();
        coresTextField = new javax.swing.JTextField();
        dataTextField = new javax.swing.JTextField();
        tipusComboBox = new javax.swing.JComboBox<>();
        nomTextField = new javax.swing.JTextField();
        amdRadioButton = new javax.swing.JRadioButton();
        CodeLabelMod = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        CoresLabel = new javax.swing.JLabel();
        PreuLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        codiLabelShow.setText("Codi:");

        nomLabelShow.setText("Nom:");

        tipusLabelShow.setText("Tipus:");

        dataLabelShow.setText("Data llençament");

        fabricantLabelShow.setText("Fabricant:");

        coresLabelShow.setText("Cores:");

        optionalLabelShow.setText("Opcionals:");

        preuLabelShow.setText("Preu:");

        igpuCheckBox.setText("IGPU");

        overclockCheckBox.setText("Overclock");

        buttonGroup1.add(intelRadioButton);
        intelRadioButton.setText("Intel");
        intelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intelRadioButtonActionPerformed(evt);
            }
        });

        coresTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coresTextFieldActionPerformed(evt);
            }
        });

        tipusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusComboBoxActionPerformed(evt);
            }
        });

        nomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(amdRadioButton);
        amdRadioButton.setText("AMD");

        CodeLabelMod.setText("Code");

        NameLabel.setForeground(new java.awt.Color(255, 51, 51));
        NameLabel.setText("Llargada minima de 5");

        DataLabel.setForeground(new java.awt.Color(255, 51, 51));
        DataLabel.setText("Llargada minima de 5");

        CoresLabel.setForeground(new java.awt.Color(255, 51, 51));
        CoresLabel.setText("S'ha de introduir un numero");

        PreuLabel.setForeground(new java.awt.Color(255, 51, 51));
        PreuLabel.setText("S'ha de introduir un numero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preuLabelShow)
                    .addComponent(optionalLabelShow)
                    .addComponent(coresLabelShow)
                    .addComponent(fabricantLabelShow)
                    .addComponent(dataLabelShow)
                    .addComponent(tipusLabelShow)
                    .addComponent(nomLabelShow)
                    .addComponent(codiLabelShow))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(intelRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amdRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(igpuCheckBox)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(overclockCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(acceptButton)
                                        .addGap(51, 51, 51)
                                        .addComponent(backButton))
                                    .addComponent(nomTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipusComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coresTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(preuTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameLabel)
                            .addComponent(DataLabel)
                            .addComponent(PreuLabel)
                            .addComponent(CoresLabel))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CodeLabelMod)
                        .addGap(206, 206, 206))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coresTextField, dataTextField, nomTextField, preuTextField, tipusComboBox});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CoresLabel, DataLabel, NameLabel, PreuLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codiLabelShow)
                    .addComponent(CodeLabelMod))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabelShow)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipusLabelShow)
                    .addComponent(tipusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabelShow)
                    .addComponent(dataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intelRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fabricantLabelShow)
                        .addComponent(amdRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coresLabelShow)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CoresLabel)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionalLabelShow)
                    .addComponent(igpuCheckBox)
                    .addComponent(overclockCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(preuLabelShow)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(preuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PreuLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(acceptButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextFieldActionPerformed

    private void intelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intelRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intelRadioButtonActionPerformed

    private void tipusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipusComboBoxActionPerformed

    private void coresTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coresTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coresTextFieldActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_acceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addDialog dialog = new addDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JLabel getCodeLabelMod() {
        return CodeLabelMod;
    }

    public JButton getAcceptButton() {
        return acceptButton;
    }

    public JRadioButton getAmdRadioButton() {
        return amdRadioButton;
    }

    public JButton getBackButton() {
        return backButton;
    }

    public JTextField getCoresTextField() {
        return coresTextField;
    }

    public JTextField getDataTextField() {
        return dataTextField;
    }

    public JCheckBox getIgpuCheckBox() {
        return igpuCheckBox;
    }

    public JRadioButton getIntelRadioButton() {
        return intelRadioButton;
    }

    public JTextField getNomTextField() {
        return nomTextField;
    }

    public JCheckBox getOverclockCheckBox() {
        return overclockCheckBox;
    }

    public JTextField getPreuTextField() {
        return preuTextField;
    }

    public JComboBox<String> getTipusComboBox() {
        return tipusComboBox;
    }

    public JLabel getCoresLabel() {
        return CoresLabel;
    }

    public JLabel getDataLabel() {
        return DataLabel;
    }

    public JLabel getNameLabel() {
        return NameLabel;
    }

    public JLabel getPreuLabel() {
        return PreuLabel;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodeLabelMod;
    private javax.swing.JLabel CoresLabel;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PreuLabel;
    private javax.swing.JButton acceptButton;
    private javax.swing.JRadioButton amdRadioButton;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel codiLabelShow;
    private javax.swing.JLabel coresLabelShow;
    private javax.swing.JTextField coresTextField;
    private javax.swing.JLabel dataLabelShow;
    private javax.swing.JTextField dataTextField;
    private javax.swing.JLabel fabricantLabelShow;
    private javax.swing.JCheckBox igpuCheckBox;
    private javax.swing.JRadioButton intelRadioButton;
    private javax.swing.JLabel nomLabelShow;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel optionalLabelShow;
    private javax.swing.JCheckBox overclockCheckBox;
    private javax.swing.JLabel preuLabelShow;
    private javax.swing.JTextField preuTextField;
    private javax.swing.JComboBox<String> tipusComboBox;
    private javax.swing.JLabel tipusLabelShow;
    // End of variables declaration//GEN-END:variables
}
